version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: teste-aiko
        network_mode: host
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: aiko-api
        restart: always
        build: .
        ports:
            - "3000:3000"
        network_mode: host
        depends_on:
            - db
        