version: '3'
services: 
  db:
    image: 'postgres:latest'
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: teste-aiko
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"