version: '3.7'

services: 

    database-postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: apiaikodb
        ports:
            - 5432:5432
        
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8081

