# Generated by Django 3.2 on 2021-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parada', '0002_alter_parada_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('paradas', models.ManyToManyField(to='parada.Parada')),
            ],
        ),
    ]
