# Generated by Django 3.2.5 on 2021-07-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_alter_parada_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linha',
            name='paradas',
        ),
    ]
