# Generated by Django 3.2.5 on 2021-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_remove_linha_paradas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
