# Generated by Django 3.2.5 on 2021-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_alter_linha_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='linha',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='linha',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
