# Generated by Django 3.2.5 on 2021-07-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_auto_20210712_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaPorLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.linha')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.parada')),
            ],
        ),
    ]
