# Generated by Django 3.2.5 on 2021-07-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_auto_20210712_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradaporlinha',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.linha'),
        ),
        migrations.AlterField(
            model_name='paradaporlinha',
            name='parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.parada'),
        ),
    ]
