# Generated by Django 3.2.5 on 2021-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0008_auto_20210712_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
