# Generated by Django 3.2.5 on 2021-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0009_alter_veiculo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
