# Generated by Django 3.2.5 on 2021-07-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0010_alter_veiculo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
