# Generated by Django 3.2.5 on 2021-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0011_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='linha',
            field=models.IntegerField(default=0),
        ),
    ]
