# Generated by Django 3.2 on 2021-04-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='linhas.linha')),
            ],
        ),
    ]
