version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=aikoBackendApi
      - DATABASE_HOST=mysql
    expose:
      - 3306
  api:
    image: aiko-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080